// This file is auto generated by build/build-entry.js
import AddressPicker from './address-picker';
import Button from './button';
import Calendar from './calendar';
import CarouselMap from './carousel-map';
import Cell from './cell';
import CellGroup from './cell-group';
import Checkbox from './checkbox';
import CheckboxGroup from './checkbox-group';
import Col from './col';
import Collapse from './collapse';
import CollapseItem from './collapse-item';
import DataProcess from './data-process';
import DatePicker from './date-picker';
import Dialog from './dialog';
import Field from './field';
import Icon from './icon';
import Image from './image';
import ImagePreview from './image-preview';
import Info from './info';
import LazyLoad from './lazy-load';
import List from './list';
import Loading from './loading';
import NavBar from './nav-bar';
import Overlay from './overlay';
import PasswordInput from './password-input';
import Picker from './picker';
import Popup from './popup';
import PullRefresh from './pull-refresh';
import Radio from './radio';
import RadioGroup from './radio-group';
import Rate from './rate';
import Row from './row';
import SafeKeyboard from './safe-keyboard';
import Search from './search';
import Slider from './slider';
import Stepper from './stepper';
import Sticky from './sticky';
import Swipe from './swipe';
import SwipeItem from './swipe-item';
import Switch from './switch';
import Tab from './tab';
import Tabbar from './tabbar';
import TabbarItem from './tabbar-item';
import Tabs from './tabs';
import Toast from './toast';
import Uploader from './uploader';

const version = '0.0.8';
const components = [
  AddressPicker,
  Button,
  Calendar,
  CarouselMap,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  Col,
  Collapse,
  CollapseItem,
  DataProcess,
  DatePicker,
  Dialog,
  Field,
  Icon,
  Image,
  ImagePreview,
  Info,
  List,
  Loading,
  NavBar,
  Overlay,
  PasswordInput,
  Picker,
  Popup,
  PullRefresh,
  Radio,
  RadioGroup,
  Rate,
  Row,
  SafeKeyboard,
  Search,
  Slider,
  Stepper,
  Sticky,
  Swipe,
  SwipeItem,
  Switch,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Toast,
  Uploader
];

const install = (Vue) => {
  components.forEach(Component => {
    if (Component.install) {
      Vue.use(Component);
    } else if (Component.name) {
      Vue.component(Component.name, Component);
    }
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export {
  install,
  version,
  AddressPicker,
  Button,
  Calendar,
  CarouselMap,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  Col,
  Collapse,
  CollapseItem,
  DataProcess,
  DatePicker,
  Dialog,
  Field,
  Icon,
  Image,
  ImagePreview,
  Info,
  LazyLoad,
  List,
  Loading,
  NavBar,
  Overlay,
  PasswordInput,
  Picker,
  Popup,
  PullRefresh,
  Radio,
  RadioGroup,
  Rate,
  Row,
  SafeKeyboard,
  Search,
  Slider,
  Stepper,
  Sticky,
  Swipe,
  SwipeItem,
  Switch,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Toast,
  Uploader
};

export default {
  install,
  version
};
