// This file is auto generated by build/build-entry.js
import ActionSheet from './action-sheet';
import AddressPicker from './address-picker';
import Badge from './badge';
import Button from './button';
import Calendar from './calendar';
import CarouselMap from './carousel-map';
import Cell from './cell';
import CellGroup from './cell-group';
import Checkbox from './checkbox';
import CheckboxGroup from './checkbox-group';
import Circle from './circle';
import Col from './col';
import Collapse from './collapse';
import CollapseItem from './collapse-item';
import CountDown from './count-down';
import DataProcess from './data-process';
import DatePicker from './date-picker';
import Dialog from './dialog';
import Divider from './divider';
import DropdownItem from './dropdown-item';
import DropdownMenu from './dropdown-menu';
import Empty from './empty';
import Field from './field';
import Grid from './grid';
import GridItem from './grid-item';
import Icon from './icon';
import Image from './image';
import ImagePreview from './image-preview';
import IndexAnchor from './index-anchor';
import IndexBar from './index-bar';
import Info from './info';
import LazyLoad from './lazy-load';
import List from './list';
import Loading from './loading';
import NavBar from './nav-bar';
import NoticeBar from './notice-bar';
import Notify from './notify';
import Overlay from './overlay';
import Pagination from './pagination';
import PasswordInput from './password-input';
import Picker from './picker';
import Popover from './popover';
import Popup from './popup';
import Progress from './progress';
import PullRefresh from './pull-refresh';
import Radio from './radio';
import RadioGroup from './radio-group';
import Rate from './rate';
import Row from './row';
import SafeKeyboard from './safe-keyboard';
import Search from './search';
import ShareSheet from './share-sheet';
import Sidebar from './sidebar';
import SidebarItem from './sidebar-item';
import Slider from './slider';
import Step from './step';
import Stepper from './stepper';
import Steps from './steps';
import Sticky from './sticky';
import Swipe from './swipe';
import SwipeCell from './swipe-cell';
import SwipeItem from './swipe-item';
import Switch from './switch';
import Tab from './tab';
import Tabbar from './tabbar';
import TabbarItem from './tabbar-item';
import Tabs from './tabs';
import Tag from './tag';
import Toast from './toast';
import TreeSelect from './tree-select';
import Uploader from './uploader';

const version = '0.1.2';
const components = [
  ActionSheet,
  AddressPicker,
  Badge,
  Button,
  Calendar,
  CarouselMap,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  Circle,
  Col,
  Collapse,
  CollapseItem,
  CountDown,
  DataProcess,
  DatePicker,
  Dialog,
  Divider,
  DropdownItem,
  DropdownMenu,
  Empty,
  Field,
  Grid,
  GridItem,
  Icon,
  Image,
  ImagePreview,
  IndexAnchor,
  IndexBar,
  Info,
  List,
  Loading,
  NavBar,
  NoticeBar,
  Notify,
  Overlay,
  Pagination,
  PasswordInput,
  Picker,
  Popover,
  Popup,
  Progress,
  PullRefresh,
  Radio,
  RadioGroup,
  Rate,
  Row,
  SafeKeyboard,
  Search,
  ShareSheet,
  Sidebar,
  SidebarItem,
  Slider,
  Step,
  Stepper,
  Steps,
  Sticky,
  Swipe,
  SwipeCell,
  SwipeItem,
  Switch,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Tag,
  Toast,
  TreeSelect,
  Uploader
];

const install = (Vue) => {
  components.forEach(Component => {
    if (Component.install) {
      Vue.use(Component);
    } else if (Component.name) {
      Vue.component(Component.name, Component);
    }
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export {
  install,
  version,
  ActionSheet,
  AddressPicker,
  Badge,
  Button,
  Calendar,
  CarouselMap,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  Circle,
  Col,
  Collapse,
  CollapseItem,
  CountDown,
  DataProcess,
  DatePicker,
  Dialog,
  Divider,
  DropdownItem,
  DropdownMenu,
  Empty,
  Field,
  Grid,
  GridItem,
  Icon,
  Image,
  ImagePreview,
  IndexAnchor,
  IndexBar,
  Info,
  LazyLoad,
  List,
  Loading,
  NavBar,
  NoticeBar,
  Notify,
  Overlay,
  Pagination,
  PasswordInput,
  Picker,
  Popover,
  Popup,
  Progress,
  PullRefresh,
  Radio,
  RadioGroup,
  Rate,
  Row,
  SafeKeyboard,
  Search,
  ShareSheet,
  Sidebar,
  SidebarItem,
  Slider,
  Step,
  Stepper,
  Steps,
  Sticky,
  Swipe,
  SwipeCell,
  SwipeItem,
  Switch,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Tag,
  Toast,
  TreeSelect,
  Uploader
};

export default {
  install,
  version
};
